"""initial double-entry schema

Revision ID: f0ea8d984406
Revises: 
Create Date: 2026-09-09 09:37:01.978429

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0001_initial_double_entry"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'INCOME', 'EXPENSE', name='accounttype'), nullable=False),
    sa.Column('subtype', sa.String(length=40), nullable=True),
    sa.Column('is_statutory', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('opening_balance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'code', name='uq_account_code')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('ix_account_user_active', ['user_id', 'is_active'], unique=False)
        batch_op.create_index('ix_account_user_type', ['user_id', 'type'], unique=False)

    op.create_table('fund_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('MONTH', 'QUARTER', 'YTD', 'ALL', name='budgetscope'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scope', 'period_start', name='uq_fund_override_period')
    )
    op.create_table('salary_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pay_period', sa.Enum('MONTHLY', 'ANNUAL', name='payperiod'), nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'account_id', 'year', 'month', name='uq_budget_period')
    )
    op.create_table('payees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('default_account_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_payee_name')
    )
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'PAYSLIP', 'OPENING', 'TRANSFER', 'IMPORT', name='entrysource'), nullable=False),
    sa.Column('source_ref', sa.String(length=64), nullable=True),
    sa.Column('reverses_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payee_id'], ['payees.id'], ),
    sa.ForeignKeyConstraint(['reverses_id'], ['journal_entries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source', 'source_ref', name='uq_entry_source_ref')
    )
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index('ix_entry_user_occurred', ['user_id', 'occurred_at'], unique=False)
        batch_op.create_index('ix_entry_user_source', ['user_id', 'source'], unique=False)
        batch_op.create_index('ix_entry_user_voided', ['user_id', 'voided_at'], unique=False)

    op.create_table('journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('line_no', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('credit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.CheckConstraint('NOT (debit > 0 AND credit > 0)', name='ck_line_single_sided'),
    sa.CheckConstraint('debit > 0 OR credit > 0', name='ck_line_non_zero'),
    sa.CheckConstraint('debit >= 0 AND credit >= 0', name='ck_line_non_negative'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['entry_id'], ['journal_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'line_no', name='uq_line_ordinal')
    )
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.create_index('ix_line_account', ['account_id'], unique=False)
        batch_op.create_index('ix_line_entry', ['entry_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.drop_index('ix_line_entry')
        batch_op.drop_index('ix_line_account')

    op.drop_table('journal_lines')
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_entry_user_voided')
        batch_op.drop_index('ix_entry_user_source')
        batch_op.drop_index('ix_entry_user_occurred')

    op.drop_table('journal_entries')
    op.drop_table('payees')
    op.drop_table('budgets')
    op.drop_table('salary_profiles')
    op.drop_table('fund_overrides')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index('ix_account_user_type')
        batch_op.drop_index('ix_account_user_active')

    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
